### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by alpenwasser** [DrewNaylor/no-downvote-display#1]
Thanks a ton for this! Works great!

Tiny question: I have somebody who'd like to use it on Firefox for Android. I dug through the MDN docs a bit and it seems the `content_scripts` key is supported since version 48, if I'm reading this page right:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts

(If I'm reading it wrong, many apologies.)

However, I'm not intimately familiar with Firefox extension development, so I figured I'd just ask if there's an underlying issue which I'm missing and which prevents porting this, or if that would be possible to do.

Thanks for the help!

**Comment by DrewNaylor** [comment]
It should work on Firefox for Android, just haven't gotten around to testing it and enabling it for Firefox on Android on the Mozilla Addons site yet. I can enable it on there and see if it works.

**Comment by DrewNaylor** [comment]
Firefox for Android has been added as a platform for the extension and it's been tested to work on Firefox for Android, although the page for it on the Mozilla Addons site says it's not listed as available on Firefox for Android. Should work if it's installed anyway, though.
